apiVersion: apps/v1
kind: Deployment
metadata:
  name: drf-backend-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drf-backend-web
  template:
    metadata:
      labels:
        app: drf-backend-web
    spec:
      containers:
      - name: drf-backend-web
        image: drf_backend_web:latest
        imagePullPolicy: Never
        command: ["/start.sh"]
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: app-env
---
apiVersion: v1
kind: Service
metadata:
  name: drf-backend-web
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: drf-backend-web