apiVersion: apps/v1
kind: Deployment
metadata:
  name: drf-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drf-redis
  template:
    metadata:
      labels:
        app: drf-redis
    spec:
      containers:
      - name: drf-redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: drf-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: drf-redis