apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: default
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: fluentd
  template:
    metadata:
      labels:
        name: fluentd
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
      - name: fluentd
        image: fluentd_nalin:latest
        imagePullPolicy: Never
        securityContext:    # this
          runAsUser: 0
        env:
          - name: FLUENTD_ARGS
            value: "--no-supervisor -q"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdocker
          mountPath: /var/lib/docker
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentd-config
          mountPath: /fluentd/etc

      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdocker
          hostPath:
            path: /var/lib/docker
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers 

        - name: fluentd-config
          configMap:
            name: fluentd-config


            

# /var/lib/docker/containers