apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: default
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/pods/default_logger-hackathon-*/*/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      <parse>
        @type "json"
        time_key "time"
        time_format "%Y-%m-%dT%H:%M:%S.%NZ"
      </parse>
    </source>

    <match kubernetes.**>
      @type http
      endpoint "http://drf-backend-web:8000/api/capture/" # Replace with your Django API endpoint
      http_method post
      serializer json
      open_timeout 5
      read_timeout 5
      flush_interval 1s  # Adjust as needed
    </match>