apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: pyeditorial-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyeditorial-postgres
  template:
    metadata:
      labels:
        app: pyeditorial-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13.2
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "abc_db"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: postgres-backups
          mountPath: /backups
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres"]
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: postgres-backups
        persistentVolumeClaim:
          claimName: postgres-backups-pvc



---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  selector:
    app: pyeditorial-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432